from app.services.position import update_position_logic
from app.services.risk import compute_portfolio_var
from app.services.alerts import run_post_trade_alerts
from app.services.feature_generation import generate_features_for_trade
from app.services.anomaly_detector import score_anomaly, train_global_anomaly_model
from app.services.market_simulator import generate_simulation_data
